### PR TITLE
Tf 0.12 compatible

### PR DESCRIPTION
**Pull request by cjpurackal**
Made the code compatible with tensorflow 0.12.

Changes are :

*control_flow_ops.While() -> control_flow_ops.while_loop()  ( This was causing the "no attribute named while" issue which was seen in some of the youtube comments)

*initialize_all_variables()  -> tf.global_variables_initializer() ( initialize_all_variables() will soon be deprecated)

### CODE REVIEW

**Comment by hb0702** [comment]
After making your change to code, I still get
Traceback (most recent call last):
  File "/home/hanbin/Desktop/Deep Leaning/Music_Generator_Demo-master/rbm_chords.py", line 87, in <module>
    x_sample = gibbs_sample(1) 
  File "/home/hanbin/Desktop/Deep Leaning/Music_Generator_Demo-master/rbm_chords.py", line 78, in gibbs_sample
    gibbs_step, [ct, tf.constant(k), x], 1, False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2629, in while_loop
    raise TypeError("parallel_iterations must be a positive integer.")
TypeError: parallel_iterations must be a positive integer.

Im using tensorflow .12

**Comment by cjpurackal** [comment]
I believe you're using the original code from this repository. The pull request hasn't been accepted, so the changes are not present in the original code.
Check out the "Files Changed" tab in this pull request to know about the changes(represented in the green region)

Specifically, change the line :
[_, _, x_sample] = control_flow_ops.While(lambda count, num_iter, *args: count < num_iter,
 gibbs_step, [ct, tf.constant(k), x], 1, False)

to 

[_, _, x_sample] = control_flow_ops.while_loop(lambda count, num_iter, *args: count < num_iter,gibbs_step, [ct, tf.constant(k), x])

**Comment by teerth** [comment]
File "rbm_chords.py", line 116, in <module>
    song = song[:np.floor(song.shape[0]/num_timesteps)*num_timesteps]

keep getting this error

**Comment by cjpurackal** [comment]
@teerth can you specify what the error is ? i don't see it in your comment

**Review by swarathesh — APPROVED** [review]

**Comment by swarathesh** [comment]
python rbm_chords.py
  File "rbm_chords.py", line 78
    [_, _, x_sample] = control_flow_ops.while_loop(lambda count, num_iter, *args: count < num_iter,
                                                                                                  ^
IndentationError: unindent does not match any outer indentation level

**Comment by swarathesh** [comment]
getting the above error after implementing the pull code

**Comment by swarathesh** [comment]
change the code you mentioned with song = song[:int(np.floor(song.shape[0]/num_timesteps)*num_timesteps)]  @teerth

**Comment by cjpurackal** [comment]
@swarathesh check the spacing in line

**Comment by swarathesh** [comment]
yep thanks @true-source

**Comment by acocalypso** [comment]
after i added your change im getting this error now:
Traceback (most recent call last):
File "rbm_chords.py", line 95, in <module>
 W_adder = tf.mul(lr/size_bt, tf.sub(tf.matmul(tf.transpose(x), h), tf.matmul(tf.transpost(x_sample), h_sample)))
AttributeError: 'module' object has no attribute 'mul'

Any idea?

EDIT:

Fixed it - according to tensorflow 1.0.0 those changed to tf.subtract, tf.multiply etc.

**Comment by llSourcell** [comment]
thanks!

**Pull request merged**
